export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_CURRENT_WEATHER_FAILED = 'GET_CURRENT_WEATHER_FAILED';
export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS';

export const GET_LIST_FORECAST = 'GET_LIST_FORECAST';
export const GET_LIST_FORECAST_FAILED = 'GET_LIST_FORECAST_FAILED';
export const GET_LIST_FORECAST_SUCCESS = 'GET_LIST_FORECAST_SUCCESS';